export const S = {
  page: { maxWidth: 1240 },
  header: { display: "flex", justifyContent: "space-between", gap: 24, alignItems: "flex-start", marginBottom: 24 },
  h1: { fontSize: 28, fontWeight: 750, margin: "0 0 8px", color: "var(--admin-text)" },
  sub: { color: "var(--admin-text-subtle)", fontSize: 14, margin: 0, maxWidth: 560, lineHeight: 1.5 },
  controls: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" as const },
  panel: { background: "var(--admin-surface)", border: "1px solid var(--admin-border)", borderRadius: 8, padding: 18, marginBottom: 24 },
  panelHead: { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "baseline", marginBottom: 16 },
  panelTitle: { fontSize: 15, color: "var(--admin-text)", fontWeight: 750, margin: 0 },
  panelMeta: { fontSize: 13, color: "var(--admin-text-subtle)" },
  importGrid: { display: "grid", gridTemplateColumns: "1fr auto", gap: 10, alignItems: "end" },
  importList: { display: "grid", gap: 12, marginTop: 14 },
  importRow: { background: "var(--admin-surface)", border: "1px solid var(--admin-border)", borderRadius: 8, padding: 12 },
  importTop: { display: "grid", gridTemplateColumns: "auto 150px 1fr 150px 150px", gap: 10, alignItems: "center", marginBottom: 10 },
  check: { width: 18, height: 18, accentColor: "var(--admin-primary)" },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12, marginBottom: 12 },
  field: { display: "flex", flexDirection: "column" as const, gap: 6 },
  label: { fontSize: 12, color: "var(--admin-text-subtle)", fontWeight: 650 },
  input: {
    background: "var(--admin-bg)",
    border: "1px solid var(--admin-border-strong)",
    borderRadius: 7,
    padding: "10px 11px",
    color: "var(--admin-text)",
    fontSize: 14,
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  select: {
    background: "var(--admin-bg)",
    border: "1px solid var(--admin-border-strong)",
    borderRadius: 7,
    padding: "10px 11px",
    color: "var(--admin-text)",
    fontSize: 14,
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  textarea: {
    background: "var(--admin-bg)",
    border: "1px solid var(--admin-border-strong)",
    borderRadius: 7,
    padding: "10px 11px",
    color: "var(--admin-text)",
    fontSize: 14,
    outline: "none",
    width: "100%",
    minHeight: 92,
    resize: "vertical" as const,
    boxSizing: "border-box" as const,
  },
  btn: (primary: boolean) => ({
    padding: "10px 14px",
    borderRadius: 7,
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    border: primary ? "none" : "1px solid var(--admin-border-strong)",
    background: primary ? "var(--admin-primary)" : "var(--admin-bg)",
    color: primary ? "var(--admin-on-primary)" : "var(--admin-text-muted)",
    whiteSpace: "nowrap" as const,
  }),
  tabs: { display: "flex", gap: 8, flexWrap: "wrap" as const, marginBottom: 18 },
  tabBtn: (active: boolean) => ({
    padding: "10px 14px",
    borderRadius: 7,
    fontWeight: 750,
    fontSize: 13,
    cursor: "pointer",
    border: `1px solid ${active ? "var(--admin-primary)" : "var(--admin-border-strong)"}`,
    background: active ? "var(--admin-primary)" : "var(--admin-surface)",
    color: active ? "var(--admin-on-primary)" : "var(--admin-text-muted)",
  }),
  stats: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 12, marginBottom: 24 },
  stat: { background: "var(--admin-surface)", border: "1px solid var(--admin-border)", borderRadius: 8, padding: 16 },
  statValue: { fontSize: 26, color: "var(--admin-primary)", fontWeight: 800 },
  statLabel: { fontSize: 12, color: "var(--admin-text-subtle)", marginTop: 3 },
  split: { display: "grid", gridTemplateColumns: "minmax(360px, 460px) 1fr", gap: 16 },
  schedule: { display: "grid", gap: 10 },
  dayCard: { background: "var(--admin-surface)", border: "1px solid var(--admin-border)", borderRadius: 8, padding: 14 },
  dayTop: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "baseline", marginBottom: 12 },
  dayTitle: { color: "var(--admin-text)", fontSize: 14, fontWeight: 800 },
  dayDate: { color: "var(--admin-text-subtle)", fontSize: 12 },
  wodTitle: { color: "var(--admin-text)", fontSize: 16, fontWeight: 800, marginBottom: 5, overflowWrap: "anywhere" as const },
  wodMeta: { color: "var(--admin-primary)", fontSize: 12, fontWeight: 800, letterSpacing: 0.5, textTransform: "uppercase" as const },
  desc: { color: "var(--admin-text-muted)", fontSize: 13, lineHeight: 1.5, marginTop: 10, whiteSpace: "pre-wrap" as const },
  chips: { display: "flex", gap: 6, flexWrap: "wrap" as const, marginTop: 12 },
  chip: { color: "var(--admin-text-muted)", background: "var(--admin-bg)", border: "1px solid var(--admin-border-strong)", borderRadius: 4, padding: "4px 8px", fontSize: 12 },
  scaling: { color: "var(--admin-text-subtle)", fontSize: 13, fontStyle: "italic", marginTop: 10, lineHeight: 1.4 },
  empty: { color: "var(--admin-text-subtle)", fontSize: 13, padding: "10px 0" },
  partGrid: { display: "grid", gap: 10, marginTop: 12 },
  partCard: { background: "var(--admin-surface)", border: "1px solid var(--admin-border)", borderRadius: 8, padding: 12 },
  partFields: { display: "grid", gridTemplateColumns: "80px 1fr 130px", gap: 10, marginBottom: 10 },
  formActions: { display: "flex", gap: 10, justifyContent: "flex-end", borderTop: "1px solid var(--admin-border)", paddingTop: 14, marginTop: 16 },
  error: { color: "var(--admin-error)", fontSize: 13, margin: "12px 0 0" },
  success: { color: "var(--admin-success)", fontSize: 13, margin: "12px 0 0" },
};
