// Auto-generated by build-gym.sh — DO NOT EDIT (restored after build)
export default {
  expo: {
    name: "NorthernGlow",
    slug: "northernglow",
    version: "1.0.0",
    orientation: "portrait",
    scheme: "northernglow",
    userInterfaceStyle: "light",
    icon: "./assets/icon.png",
    splash: {
      image: "./assets/splash.png",
      resizeMode: "contain",
      backgroundColor: "#0E7490",
    },
    ios: {
      supportsTablet: false,
      bundleIdentifier: "com.northernglow.app",
      infoPlist: {
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        backgroundColor: "#0E7490",
      },
      package: "com.northernglow.app",
    },
    plugins: [
      "expo-router",
      [
        "expo-secure-store",
        {
          faceIDPermission: "Allow NorthernGlow to access Face ID for secure login.",
        },
      ],
      "@react-native-community/datetimepicker",
      "expo-font",
    ],
    web: {
      bundler: "metro",
      output: "single",
    },
    experiments: {
      typedRoutes: true,
    },
    newArchEnabled: true,
    extra: {
      gymId: "mh7cqfx7wkstt6rx28xnp7qehn84vfb4",
      router: {},
      eas: {
        projectId: "83011cc3-770b-4dfc-a844-18100f134c30",
      },
    },
    owner: "yacoub89",
  },
};
